name: Ubuntu és Debian csomag

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Forráskód kiolvasása
        uses: actions/checkout@v4
      - name: Debian-csomag felépítése
        run: bash build_deb.sh
      - name: Debian-csomag mentése
        uses: actions/upload-artifact@v4
        with:
          name: debian-csomag
          path: dist/*.deb
          if-no-files-found: error
